### ISSUE TITLE
grpc discovery

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-vscode-plugin#108]
1. create a middleware if possible that saves as the GRPC code object in the span attributes to allow its discovery by the plugin. (Go is high priority). They are using: https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/google.golang.org/grpc/otelgrpc
2. If not possible implement discovery in plugin (also prioritize Go)

**Comment by arik-dig** [comment]
the middleware ( grpc interceptor ) was implemented in this PR:
https://github.com/digma-ai/otel-go-instrumentation/pull/4
