### ISSUE TITLE
Jaeger embedded view

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-vscode-plugin#221]
Add Jaeger UI integration with possibility of two way navigation between traces and insights

Span link behavior:
1. Get all span elements from DOM, and extract span name and instrumentation(see attached screenshot)
2. In a magic way use the  SpanSearch class in order to get spans locations, I guess it will return results only for discoverable spans.
3. I guess at this point we'll have all the information we need for navigation

![Image](https://user-images.githubusercontent.com/1392692/206509223-cb565392-e740-4b4e-9157-787cf8e765d9.png)

**Comment by kshmidt-digma** [comment]
**Prerequsities**
To make it possible for the webview with Jaeger-UI to send requests to the `jaeger-query` with CORS, `jaeger` container need to be started with the following CLI flag `--query.additional-headers "Access-Control-Allow-Origin: *"`

**Comment by shaykeren** [comment]
span code object id format:

**span:**<INSTRUMENTATION_LIBRARY_NAME>**$_$**<SPAN_NAME>
