### ISSUE TITLE
Recent Activity Panel  -  See feedback in Digma when performing an action

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-vscode-plugin#250]
Context: 
The user performs an action, for example: Calling an API via swagger, running a test, clicking a button in the UI etc. 

Goal:
1. To show the user that Digma is working and captured this event
2. To provide links to all related information about the action he just performed so he can easily navigate to it
3. To quickly see the insights related to the flow I just performed

Recent activity view:
insight icons - show only high-priority insights
trace button - should open jaeger for this specific trace
show last 10 trace flows (live view)
see mockup for more details about the location of the view.

https://www.figma.com/file/ncRV3XUn1VltctY8LjlJFX/Digma-Design-System?node-id=15%3A3461&t=TfrQuyUSAajD0tp1-1

**Comment by arik-dig** [comment]
I've snippeted a screenshot from Figma:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/104715391/214266130-c73e9c43-6cc2-4243-9008-1a5444aadf7b.png">

**Comment by arik-dig** [comment]
@doppleware lets say a Trace as few flows, and each ends with different span, so which of the flows(latest span) should we choose to display?

**Comment by doppleware** [comment]
The logic is to group by start *entry* span and end *entry* span.
So that if one flow stars with GET / and ends with CONSUME BLAH and another starts with GET / and ends with POST /Users they are different flows

**Comment by arik-dig** [comment]
@doppleware What happens when flow ends with some internal span?

**Comment by doppleware** [comment]
It doesn't matter as we only use Entry Spans to hash it

**Comment by arik-dig** [comment]
@doppleware regarding the returned insights (icons), per record view:

1) Whats the minimal importance required? we have Enum
```
    public enum InsightImportance
    {
        Spam = 9,
        Clutter = 8,
        NotInteresting= 7,
        Info = 6,
        Interesting = 5,
        Important = 4,
        HighlyImportant =3,
        Critical = 2,
        ShowStopper = 1,
    }
```
So I guess minimal for display is **lower equal to 4 (Important)** ?

2. If I understand correctly we want to show aggregated icon, and not per code object(and/or span), for example if there's an error hotspot on few spans, we will show the ICON only once, right?

3. Assuming 2 is correct, would we want to return the related code objects, and allow in the UI to navigate to that code object?
I think its a winner feature, but would require the UI to make a pop-up for the related code objects (assuming there could be more than one per insight)

**Comment by doppleware** [comment]
Cow cow....
First, yes we want to show insights of 4 and up, show the icon only once.
For now the behavior I would like to implement is have the entry span be a link to the endpoint code location (already implemented in vscode, and already returned as info from server).
In the next phase we can see how to enable a list of code locations for insights.
